"""Added initial Sensor tables

Revision ID: a6bda57a523c
Revises: 
Create Date: 2025-09-12 21:33:09.976393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6bda57a523c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('reading_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.CheckConstraint('value >= 0', name='value_check'),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_table('sensors',
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.Enum('Temperature', 'Vibration', 'Pressure', 'Noise', name='sensor_type_enum'), nullable=False),
    sa.Column('unit', sa.String(length=10), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('sensor_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
